services:
  web:
    build: .
    image: ipmi-ip-server
    restart: always
    ports:
      - "8799:8799"
    devices:
      - "/dev/ipmi0:/dev/ipmi0"
  godns:
    image: timothyye/godns
    depends_on:
      - web
    restart: always
    volumes:
      - ./config.json:/config.json